# Location
latitude: 59.932866
longitude: 10.763931
elevation: 23

# Security
http_password: fredrik
ssl_certificate: /config/fullchain.pem  # Optional for later
ssl_key: /config/privkey.pem           # Optional for later

# MQTT
mqtt_username: olav
mqtt_password: fredrik

# Device Credentials
apple_tv_credentials: TBD_during_setup

# Network
homebridge_ip: 192.168.0.97
lg_tv_ip: 192.168.0.98

# Database
postgres_url: postgresql://homeassistant:homeassistant@postgres/homeassistant